name: CI

on:
  push: 
    branches:
      - 'v[0-9].[0-9]'
    tags:
      - 'latest'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        run: |
          if [[ $(git log -1 --pretty=%B) == *"#NORUN"* ]]; then
            echo "Commit message contains #NORUN, exiting workflow."
            exit 0
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "latest"
          force_push_tag: true
          message: "Latest release"
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          tag: "latest"
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "body.md"

      - name: Install Railway
        run: npm i -g @railway/cli
