name: CI

on:
  push: 
    branches:
      - 'v[0-9].[0-9]'
    tags:
      - 'latest'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        run: |
          if [[ $(git log -1 --pretty=%B) == *"#NORUN"* ]]; then
            echo "Commit message contains #NORUN, exiting workflow."
            exit 0
          fi
      - name: Checkout code
        uses: actions/checkout@v4
  release:
    needs: build
    runs-on: ubuntu-latest